language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
install:
  - pip install flake8==2.1.0 pep8==1.5.6
  - python setup.py install
  - pip list
  - flake8 --version
script:
  - python setup.py test -q
  - flake8 pyflakes setup.py
matrix:
  allow_failures:
    - python: pypy
